import { Linking, Share } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import type { UserTransaction } from "../types";

type ReceiptIdentity = {
  name: string;
  userId: string;
};

type ReceiptOptions = {
  transaction: UserTransaction;
  payer: ReceiptIdentity;
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export function formatReceiptDate(timestamp: string): string {
  return new Date(timestamp).toLocaleString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function getTransactionStatusLabel(transaction: UserTransaction): string {
  if (transaction.status === "failed") return "Rejected";
  if (transaction.status === "pending") return "Pending Offline";
  if (transaction.status === "synced" && transaction.voucherData?.used) return "Verified Offline";
  if (transaction.status === "synced") return "Backed Up";
  if (transaction.category === "voucher_refund") return "Refunded";
  if (transaction.type === "credit") return "Completed";
  return "Processed";
}

function getMerchantLabel(transaction: UserTransaction): string {
  return (
    transaction.merchantName ||
    transaction.merchantId ||
    transaction.description.replace(/^Paid to\s+/i, "") ||
    "Merchant"
  );
}

function buildReceiptHtml({ transaction, payer }: ReceiptOptions): string {
  const statusLabel = getTransactionStatusLabel(transaction);
  const merchantLabel = getMerchantLabel(transaction);
  const voucherLabel = transaction.voucherId || transaction.id;
  const amountLabel = `₹${Math.abs(transaction.amount).toLocaleString("en-IN")}`;
  const statusColor =
    transaction.status === "failed"
      ? "#b42318"
      : transaction.status === "pending"
      ? "#b54708"
      : "#027a48";
  const statusBg =
    transaction.status === "failed"
      ? "#fee4e2"
      : transaction.status === "pending"
      ? "#fef0c7"
      : "#dcfae6";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 28px; background: #f5f3ff; color: #1f2433; }
    .card { background: #ffffff; border-radius: 18px; padding: 24px; box-shadow: 0 8px 24px rgba(96, 89, 166, 0.12); }
    .hero { background: linear-gradient(135deg, #6f63ff, #8b5cf6); color: #fff; border-radius: 18px; padding: 22px; margin-bottom: 18px; }
    .hero h1 { margin: 0 0 8px 0; font-size: 24px; }
    .hero p { margin: 0; font-size: 13px; opacity: 0.92; }
    .amount { font-size: 36px; font-weight: bold; margin: 18px 0 8px; }
    .badge { display: inline-block; padding: 8px 16px; border-radius: 999px; background: ${statusBg}; color: ${statusColor}; font-weight: 700; font-size: 13px; }
    table { width: 100%; border-collapse: collapse; margin-top: 22px; }
    td { padding: 11px 0; border-bottom: 1px solid #ece8ff; font-size: 14px; }
    .label { color: #70758b; width: 38%; }
    .value { text-align: right; font-weight: 700; color: #1f2433; }
    .note { margin-top: 18px; font-size: 13px; color: #5f6475; line-height: 1.5; }
    .footer { margin-top: 20px; text-align: center; font-size: 11px; color: #8b8fa6; }
  </style>
</head>
<body>
  <div class="hero">
    <h1>Payment Receipt</h1>
    <p>Offline Pay secure transaction summary</p>
    <div class="amount">${amountLabel}</div>
    <span class="badge">${escapeHtml(statusLabel)}</span>
  </div>
  <div class="card">
    <table>
      <tr><td class="label">From</td><td class="value">${escapeHtml(payer.name)}</td></tr>
      <tr><td class="label">User ID</td><td class="value">${escapeHtml(payer.userId || "N/A")}</td></tr>
      <tr><td class="label">To</td><td class="value">${escapeHtml(merchantLabel)}</td></tr>
      <tr><td class="label">Amount</td><td class="value">${amountLabel}</td></tr>
      <tr><td class="label">Time</td><td class="value">${escapeHtml(formatReceiptDate(transaction.timestamp))}</td></tr>
      <tr><td class="label">Voucher</td><td class="value">${escapeHtml(voucherLabel)}</td></tr>
      <tr><td class="label">Signature</td><td class="value">ECDSA secp256k1</td></tr>
      <tr><td class="label">Status</td><td class="value">${escapeHtml(statusLabel)}</td></tr>
    </table>
    <div class="note">
      This receipt is generated from the current app record. Signed vouchers are verified during sync and protect against tampering or replay.
    </div>
    <div class="footer">Generated by Offline Pay on ${escapeHtml(formatReceiptDate(new Date().toISOString()))}</div>
  </div>
</body>
</html>`;
}

export async function generateReceiptPdf(options: ReceiptOptions): Promise<string> {
  const html = buildReceiptHtml(options);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  return uri;
}

export async function shareReceiptPdf(options: ReceiptOptions): Promise<void> {
  const uri = await generateReceiptPdf(options);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Share or save payment receipt",
      UTI: "com.adobe.pdf",
    });
    return;
  }

  await Share.share({
    title: "Payment Receipt",
    message: `Payment receipt ready: ${uri}`,
  });
}

export async function shareReceiptOnWhatsApp(options: ReceiptOptions): Promise<void> {
  const { transaction, payer } = options;
  const lines = [
    "Offline Pay Receipt",
    "",
    `From: ${payer.name}`,
    `To: ${getMerchantLabel(transaction)}`,
    `Amount: ₹${Math.abs(transaction.amount).toLocaleString("en-IN")}`,
    `Time: ${formatReceiptDate(transaction.timestamp)}`,
    `Voucher: ${transaction.voucherId || transaction.id}`,
    `Status: ${getTransactionStatusLabel(transaction)}`,
    "Signature: ECDSA secp256k1",
  ];
  const message = lines.join("\n");
  const encoded = encodeURIComponent(message);
  const appUrl = `whatsapp://send?text=${encoded}`;
  const webUrl = `https://wa.me/?text=${encoded}`;

  try {
    const canOpen = await Linking.canOpenURL(appUrl);
    if (canOpen) {
      await Linking.openURL(appUrl);
      return;
    }
    await Linking.openURL(webUrl);
  } catch {
    await Share.share({
      title: "Payment Receipt",
      message,
    });
  }
}
